In [2]:
import pandas as pd
# Specify the file path
file_path = r"C:\Users\VAMSI\Desktop\project\Bird_Monitoring_Data_FOREST.XLSX"

# Read the Excel file with multiple sheets
excel_data = pd.ExcelFile(file_path)

# Get all sheet names
sheet_names = excel_data.sheet_names

# Read data from all sheets into a dictionary
sheets_dict = {sheet: excel_data.parse(sheet) for sheet in sheet_names}

In [3]:
list_of_keys = list(sheets_dict.keys())

KEYS = [None] * len(sheets_dict.keys())
i=0
for each_dict in sheets_dict.keys() :
    KEYS[i] = sheets_dict[each_dict]
    i+=1

In [4]:
#no of rows and columns in dataframe
def total_rows(sheet_name):
    total_rows = sheet_name.shape[0]
    return total_rows
def total_columns(sheet_name):  
    total_columns = sheet_name.shape[1]
    return total_columns

In [5]:
def check_repeated_distinct_value_columns(sheet_name):
    count_of_repeatedvalues=0
    count_distinct=0   
    for everycolumn in sheet_name.columns :
        for i in range(total_rows(sheet_name)):
            first_value =sheet_name[everycolumn].loc[0]
            if first_value == sheet_name[everycolumn].loc[i]:
                count_of_repeatedvalues+=1    
        if count_of_repeatedvalues == total_rows(sheet_name):
           print("repeated values in :",everycolumn)
            
        
        if sheet_name[everycolumn].nunique() == len(sheet_name[everycolumn]):
            print(everycolumn , "has distinct values")
        else :
            count_distinct+=1
            if count_distinct==29:
               print("None of the columns have distinct values")

def check_null_values(sheet_name):
    for everycolumn in sheet_name.columns :
      is_null = sheet_name[everycolumn].isnull().any()
      if  is_null == True:
            print(f"Column '{everycolumn}' has {sheet_name[everycolumn].isnull().sum()} null values")

In [6]:
if __name__ == "__main__": 
    for j in range(11):
        print("sheet",list_of_keys[j])
        print("")
        print("total_rows_in_this_sheet:",total_rows(KEYS[j]))
        print("total_columns_in_this_sheet:",total_columns(KEYS[j]))
        print("")
        check_repeated_distinct_value_columns(KEYS[j])
        check_null_values(KEYS[j])
        print("")

sheet ANTI

total_rows_in_this_sheet: 333
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 333 null values
Column 'Distance' has 5 null values
Column 'Sex' has 221 null values
Column 'AcceptedTSN' has 1 null values

sheet CATO

total_rows_in_this_sheet: 805
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 805 null values
Column 'Distance' has 4 null values
Column 'Sex' has 366 null values
Column 'AcceptedTSN' has 2 null values

sheet CHOH

total_rows_in_this_sheet: 2202
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 2202 null values
Column 'Distance' has 30 null values
Column 'Sex' has 1511 null values
Column 'AcceptedTSN' has 1 null values

sheet GWMP

total_rows_in_this_sheet: 386
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 348 null values
Column 'Distance' has 14 null values
Column 'Sex' has 287 null values
Column 'AcceptedTSN' has 1 null values

sheet HAFE

total_rows_in_this_sheet: 422
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 422 null values
Column 'Distance' has 11 null values
Column 'Sex' has 268 null values
Column 'AcceptedTSN' has 4 null values

sheet MANA

total_rows_in_this_sheet: 465
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 465 null values
Column 'Distance' has 5 null values
Column 'Sex' has 273 null values

sheet MONO

total_rows_in_this_sheet: 370
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 370 null values
Column 'Distance' has 4 null values
Column 'Sex' has 225 null values

sheet NACE

total_rows_in_this_sheet: 684
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
None of the columns have distinct values
Column 'Distance' has 11 null values
Column 'Sex' has 470 null values

sheet PRWI

total_rows_in_this_sheet: 2463
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 2463 null values
Column 'ID_Method' has 1 null values
Column 'Distance' has 2 null values
Column 'Sex' has 1270 null values

sheet ROCR

total_rows_in_this_sheet: 289
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 289 null values
Column 'Distance' has 5 null values
Column 'Sex' has 191 null values

sheet WOTR

total_rows_in_this_sheet: 127
total_columns_in_this_sheet: 29

repeated values in : Admin_Unit_Code
repeated values in : Sub_Unit_Code
None of the columns have distinct values
Column 'Sub_Unit_Code' has 127 null values
Column 'Distance' has 1 null values
Column 'Sex' has 101 null values